Normalize dynamically created classes by CGLIB to their canonical form
This fixes following issue (occuring in QueryDSL):

Q_2045977532_1275614662_1275614662.java:3: error: cannot find symbol
    public example.ExampleClass$$EnhancerByMockitoWithCGLIB$$45c738ca a1;
                  ^
  symbol:   class ExampleClass$$EnhancerByMockitoWithCGLIB$$45c738ca
  location: package example

As this class is dynamically generated, it can't be found at compile-time.
Because it basically is a proxy for the underlying object, use its super class
as normalized form, which solves the compile error.